packages:
  - 'packages/jsondiff.dev'
  - 'packages/siesta/packages/siesta'
  - 'packages/siesta/packages/chained-iterator'
  - 'packages/siesta/packages/typescript-mixin-class'
  - 'packages/siesta/packages/typescript-serializable-mixin'
  - 'packages/siesta/packages/chronograph'
